spring.application.name=cinema-management

# Cau hinh ket noi MySQL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CinemaManagementDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cau hinh Hibernate (Tu dong cap nhat bang va in ra cau lenh SQL de de kiem tra)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect